Update pcd_tools.py for get_convex_hull
Renamed xyz to pcd_xyz
Was getting below error when using 'dim=3D' because xy only defined when dim=2D. So i copied that line to the elif statement.
hull_xy = xy[hull.vertices, :]
UnboundLocalError: local variable 'xy' referenced before assignment